chcp 65001
mkdir %Temp%\downloadTemp
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/src/7z.exe" "%Temp%\downloadTemp\7z.exe"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/src/7z.dll" "%Temp%\downloadTemp\7z.dll"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.001" "%Temp%\downloadTemp\7年级下册英语课件.zip.001"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.002" "%Temp%\downloadTemp\7年级下册英语课件.zip.002"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.003" "%Temp%\downloadTemp\7年级下册英语课件.zip.003"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.004" "%Temp%\downloadTemp\7年级下册英语课件.zip.004"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.005" "%Temp%\downloadTemp\7年级下册英语课件.zip.005"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.006" "%Temp%\downloadTemp\7年级下册英语课件.zip.006"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.007" "%Temp%\downloadTemp\7年级下册英语课件.zip.007"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.008" "%Temp%\downloadTemp\7年级下册英语课件.zip.008"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.009" "%Temp%\downloadTemp\7年级下册英语课件.zip.009"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.010" "%Temp%\downloadTemp\7年级下册英语课件.zip.010"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.011" "%Temp%\downloadTemp\7年级下册英语课件.zip.011"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.012" "%Temp%\downloadTemp\7年级下册英语课件.zip.012"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.013" "%Temp%\downloadTemp\7年级下册英语课件.zip.013"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.014" "%Temp%\downloadTemp\7年级下册英语课件.zip.014"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.015" "%Temp%\downloadTemp\7年级下册英语课件.zip.015"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.016" "%Temp%\downloadTemp\7年级下册英语课件.zip.016"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.017" "%Temp%\downloadTemp\7年级下册英语课件.zip.017"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.018" "%Temp%\downloadTemp\7年级下册英语课件.zip.018"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.019" "%Temp%\downloadTemp\7年级下册英语课件.zip.019"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.020" "%Temp%\downloadTemp\7年级下册英语课件.zip.020"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.021" "%Temp%\downloadTemp\7年级下册英语课件.zip.021"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.022" "%Temp%\downloadTemp\7年级下册英语课件.zip.022"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.023" "%Temp%\downloadTemp\7年级下册英语课件.zip.023"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.024" "%Temp%\downloadTemp\7年级下册英语课件.zip.024"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.025" "%Temp%\downloadTemp\7年级下册英语课件.zip.025"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.026" "%Temp%\downloadTemp\7年级下册英语课件.zip.026"
bitsadmin /transfer n "http://htfc786.github.io/testnetdesk/7年级下册英语课件.zip/7年级下册英语课件.zip.027" "%Temp%\downloadTemp\7年级下册英语课件.zip.027"
%Temp%\downloadTemp\7z x -o. "%Temp%\downloadTemp\7年级下册英语课件.zip.001"
del /s /q %Temp%\downloadTemp
rd /s /q %Temp%\downloadTemp
exit
